[package]
name = "snor"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
eframe = "0.36"
git2 = { version = "0.21.0", default-features = false, features = ["vendored-libgit2"] }
ignore = "0.4.33"
notify = "8.2.0"
portable-pty = "0.9.0"
ropey = "1.6.1"
vt100 = "0.16.2"
walkdir = "2.5.0"
